Remove references to `convert_raw_tracks_to_h5` and update docs
DeepLabCut/DeepLabCut pull request #1553
Opened 2021-10-19 10:12 UTC by jeylau

Some references to `convert_raw_tracks_to_h5` had been left behind. It's now exactly the job done by `stitch_tracklets`, so they have been cleaned up. The docs have also been updated to describe the possibility to extract outliers from the _full.pickle right after video analysis.

2021-10-19 11:09 UTC, MMathisLab commented
why don't we package this as a single call: 
```python
from deeplabcut.refine_training_dataset import find_outliers_in_raw_data
find_outliers_in_raw_data(config_path, pickle_file, video_file)
```
where pickle_file is the `_full.pickle` one obtains after video analysis.
Flagged frames will be added to your collection of images in the corresponding labeled-data folders for you to label.

2021-10-19 11:47 UTC, jeylau commented
What do you mean? It is wrapped in a single function call.

2021-10-19 17:33 UTC, AlexEMG approved these changes

2021-10-19 19:53 UTC, MMathisLab commented
I mean: `deeplabcut.find_outliers_in_raw_data(config_path, pickle_file, video_file)`

2021-10-20 17:36 UTC, MMathisLab requested changes
see comment in thread

2021-10-21 13:51 UTC, jeylau commented
> see comment in thread

Updated!

2021-10-21 16:09 UTC, MMathisLab approved these changes

2021-10-21 16:09 UTC, merged