Uniform analyze_videos API
DeepLabCut/DeepLabCut pull request #1567
Opened 2021-11-05 07:43 UTC by jeylau

Automatically chain video analysis, tracking & stitching with the new argument `auto_track=True`. This produces the final h5 file in one function call, equivalent to the behavior of `analyze_videos` in single-animal projects. Note that `track_method` has now been moved to `default_track_method` in the config.yaml, simplifying many core functions (and some GUI tabs).

2021-11-05 13:54 UTC, MMathisLab commented
@jeylau would this https://github.com/DeepLabCut/DeepLabCut/pull/1556 still be required then, or?

2021-11-05 14:07 UTC, jeylau commented
@MMathisLab, yes, because whether functions are chained or not it is still desirable to optimize assembly/tracking when there is only an animal ☺️

2021-11-05 16:48 UTC, MMathisLab requested changes

2021-11-05 16:48 UTC, MMathisLab commented on deeplabcut/pose_estimation_tensorflow/predict_videos.py
> +    track_method = cfg.get("default_track_method", "ellipse")
should we have a catch for older projects, i.e., if cfg.get("default_track_method") = false, then write it into config.yaml and set default as ellipse?

2021-11-05 16:48 UTC, MMathisLab commented on docs/maDLC_UserGuide.md
> +*NEW* in 2.2.1: `deeplabcut.analyze_videos` has a new argument `auto_track=True`, chaining pose estimation, tracking, and stitching in a single function call with defaults we found to work well. Thus
I think we might want to bump to 2.2.0.3 this week; keep 2.2.1 for full clean version

2021-11-06 11:32 UTC, jeylau commented on deeplabcut/pose_estimation_tensorflow/predict_videos.py
> +    track_method = cfg.get("default_track_method", "ellipse")
Good idea! I've just added it 😊

2021-11-07 17:10 UTC, MMathisLab approved these changes

2021-11-07 17:16 UTC, MMathisLab commented
okay looks good to me once new merge conflict from other PR merged! thanks @jeylau 💜

2021-11-07 17:19 UTC, jeylau commented
@MMathisLab, resolved ☺️

2021-11-17 17:24 UTC, AlexEMG requested changes
Great update! 

Esp. also adding the default_track_method to the config.yaml

However, I'm not sure why we remove track_method as a parameter, just because there is a default now in the config? As for other parameters, users can usually overwrite the default by passing it directly to the function?

2021-11-17 17:48 UTC, AlexEMG commented
Put some draft here: https://github.com/DeepLabCut/DeepLabCut/commit/9dfb8afbd2f138f1a9ccf3743e4a041feefb4b29

2021-11-17 20:13 UTC, jeylau commented
@AlexEMG, I like it when you're in the refactoring mood 😁

2021-11-17 20:14 UTC, jeylau commented
Could you run black on your changes and merge them into mine?

2021-11-21 15:54 UTC, MMathisLab commented
@jeylau not sure @AlexEMG can merge into your github, since it's not a DLC branch; can you add his edits and merge, so this PR can be merged? thanks!

2021-12-09 17:32 UTC, AlexEMG approved these changes

2021-12-20 20:31 UTC, merged