Cross-platform labelling and training
DeepLabCut/DeepLabCut pull request #1584
Opened 2021-11-19 15:14 UTC by jeylau

Image paths were stored with OS-specific path separators, making labeling/training hard across platforms (e.g., forcing users to create the training data with the machine they train their models on, and occasionally to convert their data). Paths are now stored without separators as MultiIndex (labeled-data, subfolder, imagename), making indexing/merging DataFrames easy and robust; only upon reading an image are the paths reconstructed.
I tested the GUIs as well ☺️

2021-11-22 15:17 UTC, MMathisLab requested changes
maybe just leave term in and add depreciation warning, i..e, it becomes a dummy variable, but then people won't get the error invalid input , etc etc (i..e, in our colab notebooks, etc)

2021-11-22 15:17 UTC, MMathisLab commented on deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
> -    windows2linux=False,
maybe we should leave, but keep false / make a depreciation warning, as I imagine some people pass this in their code quite a bit?

2021-11-25 08:41 UTC, jeylau commented on deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
> -    windows2linux=False,
Great point, I'll add the warning!

2021-11-25 16:44 UTC, AlexEMG requested changes
- let's add some tests 
- update the examples

2021-12-09 12:28 UTC, AlexEMG approved these changes

2021-12-09 12:30 UTC, merged