adds frame extraction to add_new_videos
DeepLabCut/DeepLabCut pull request #1660
Opened 2022-02-01 23:56 UTC by louisadamian

Adds frame extraction to add_new_videos for **only** the newly added videos. Modifies extract_frames to accept an optional list of strings containing paths, when that list is not empty extract_frames only extracts frames for the videos at those paths.

Currently there is no way to extract frames for only videos added after initial model creation with user input in the command line.

2022-02-04 14:23 UTC, jeylau commented
Thanks @louisadamian for the contribution! I like that behavior of auto-extracting frames upon adding new videos. We may still want to be able to turn it off for the people who extract their frames manually via the GUI, what do you think @MMathisLab?

2022-02-04 14:26 UTC, louisadamian commented
I can definitely add an `extract_frames` optional boolean argument

2022-02-09 19:57 UTC, intergalactic-mammoth requested changes
Nice stuff @louisadamian thanks for the contribution :) I mentioned some minor things

2022-02-09 19:57 UTC, intergalactic-mammoth commented on deeplabcut/create_project/add.py
> +        "New videos were added to the project and frames have been extracted for labeling!"
You might want to keep the new print statement within the `if` and put the original print statement in an `else` (so the message is correct depending on the bool value)

2022-02-09 19:57 UTC, intergalactic-mammoth commented on deeplabcut/generate_training_dataset/frame_extraction.py
> +            A list of the string containing full paths to videos to extract frames for. If this is left as None all videos in the config file will have frames extracted.
minor typo here "A list of the string containing..." --> "A list of string**s** containing..."

2022-02-14 17:00 UTC, louisadamian commented
thanks @intergalactic-mammoth

2022-02-25 13:37 UTC, intergalactic-mammoth requested changes

2022-02-25 13:37 UTC, intergalactic-mammoth commented on deeplabcut/create_project/add.py
> +        "New videos were added to the project and frames have been extracted for labeling!"
Is this fixed? If I'm not mistaken now the function will print `New videos were added to the project and frames have been extracted for labeling` even if `extract_frames` is False.

If it is false it should still print `New videos were added to the project! Use the function 'extract_frames' to select frames for labeling` no?

Or am I missing something?

2022-02-26 06:04 UTC, louisadamian commented
@intergalactic-mammoth my bad. It's fixed now.

2022-02-27 13:41 UTC, intergalactic-mammoth commented
> @intergalactic-mammoth my bad. It's fixed now.

Nice! 🙌🔥

Maybe keep this part `Use the function 'extract_frames' to select frames for labeling` so that people can still get directions on what to do next ;)

Otherwise looks great to me!

2022-02-28 16:44 UTC, intergalactic-mammoth approved these changes

2022-02-28 17:37 UTC, intergalactic-mammoth commented on deeplabcut/create_project/add.py
> +            "New videos were added to the project! use Use the function 'extract_frames' to select frames for labeling."
typo -> "use Use"

2022-03-08 15:44 UTC, AlexEMG approved these changes

2022-03-10 12:19 UTC, jeylau approved these changes

2022-03-10 14:29 UTC, merged