Clean up requirements.txt
DeepLabCut/DeepLabCut pull request #1678
Opened 2022-02-09 07:51 UTC by jeylau

- [x] Get rid of moviepy (which prevents users from having numpy >= 1.20, also causing errors with TF at times)
- [x] Remove jupyter-books (it's already being installed automatically when publishing our docs)
- [x] Ensure scikit-learn >= 1.0
- [x] Pin tables to their newest release (notably with support for numpy 1.21 and HDF5 1.12)

2022-02-09 09:27 UTC, intergalactic-mammoth approved these changes
i like removing the need to update things in two places :muscle: :rocket:

2022-02-10 14:48 UTC, MMathisLab requested changes
left one comment, then great!

2022-02-10 14:48 UTC, MMathisLab commented on setup.py
> +requirements = []
is this required, or why the addition? @jeylau

2022-02-10 15:03 UTC, jeylau commented on setup.py
> +requirements = []
My bad, I had undone the commit but this left this part. I'll remove it :)

2022-02-10 15:17 UTC, MMathisLab approved these changes

2022-02-11 16:31 UTC, merged