Doc fix
DeepLabCut/DeepLabCut pull request #1699
Opened 2022-02-22 12:22 UTC by intergalactic-mammoth

Removed double entry and fixed `multianimal:True` to `multianimal:False` on the [User Overview Guide](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/UseOverviewGuide.md)

From this issue: https://github.com/DeepLabCut/DeepLabCut/issues/1696

2022-02-23 11:13 UTC, MMathisLab requested changes, later dismissed

2022-02-23 11:13 UTC, MMathisLab commented on docs/UseOverviewGuide.md
> +   - quick start: when you `create_new_project` just set the flag `multianimal=False`. You still get lots of upgrades!
this is not correct; it is written correctly. You can use PAFs with single animals, but MA must be set to TRUE.

2022-02-23 12:50 UTC, intergalactic-mammoth commented
@MMathisLab  oh I see, I was confused. I re-typed it so it is a bit more explicit, let me know if that works

2022-02-23 12:57 UTC, MMathisLab commented
most users will not know what this means; I prefer to leave it as it was ;)

2022-02-24 09:35 UTC, MMathisLab commented
well, you can leave open as to fix the typo ;)

2022-03-08 11:55 UTC, MMathisLab approved these changes

2022-03-08 11:55 UTC, merged