Update repo org name in docs from "AlexEMG" to "DeepLabCut"
DeepLabCut/DeepLabCut pull request #1781
Opened 2022-04-16 04:03 UTC by rahulporuri

The ownership of the "DeepLabCut" repository seems to have changed from the user "AlexEMG" to the organization "DeepLabCut" at some point in the past but a number of links still link to the old "AlexEMG" repository. The links aren't broken but they do add unnecessary confusion.

The changes made in this commit were a simple automated search-and-replace "AlexEMG" with "DeepLabCut". After the automated search-and-replace using my editor (VS Code), I manually checked all of the links.

In the process of checking the links manually, I came across a number of broken links, which I have updated/fixed.

2022-04-16 04:09 UTC, rahulporuri commented on _config.yml
> +  colab_url: "https://colab.research.google.com/github/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb"
fixed this broken link

2022-04-16 04:09 UTC, rahulporuri commented on docs/recipes/nn.md
> +When you `create_training_dataset` [you have several options](https://github.com/DeepLabCut/DeepLabCut/wiki/DOCSTRINGS#create_training_dataset) on what types of augmentation to use.
fixed this broken link

2022-04-16 04:09 UTC, rahulporuri commented on examples/COLAB/COLAB_DEMO_mouse_openfield.ipynb
> +        "#more info and there are more things you can set: https://github.com/DeepLabCut/DeepLabCut/wiki/DOCSTRINGS#train_network\n",
fixed this broken link - all other changes in this notebook were because of VS Code

2022-04-16 04:09 UTC, rahulporuri commented on examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb
> +        "#more info and there are more things you can set: https://github.com/DeepLabCut/DeepLabCut/wiki/DOCSTRINGS#train_network\n",
fixed this broken link - all other changes in this notebook were because of VS Code

2022-04-16 04:09 UTC, rahulporuri commented on docs/standardDeepLabCut_UserGuide.md
> +Please also see the following page on selecting models: https://deeplabcut.github.io/DeepLabCut/docs/recipes/nn.html#what-neural-network-should-i-use-trade-offs-speed-performance-and-considerations
fixed this broken link

2022-04-16 04:11 UTC, rahulporuri commented
@AlexEMG I am unable to assign a reviewer to this repository as mentioned in the "Contributing" guide so i'll leave that to you and your team.

2022-04-20 05:37 UTC, rahulporuri commented
@MMathisLab and @AlexEMG sorry for being pushy but can you tell me by when I can expect a review? I have a few more documentation related PRs that I would like to make over the upcoming weekend and I was hoping to work on them after hearing from you on this PR.

2022-04-22 10:56 UTC, MMathisLab commented
@rahulporuri can you remove the changes to the colab notebooks, then otherwise rest look fine, thanks!

2022-04-22 10:57 UTC, MMathisLab requested changes
please remove colab notebook edits, otherwise approved! thanks!

2022-04-22 15:48 UTC, rahulporuri commented
@MMathisLab thanks for the comment/review! I removed the unrelated changes to colab notebooks - the broken links are still fixed though.

2022-04-22 15:53 UTC, rahulporuri commented
@MMathisLab would you accept PRs that format/update docstrings (e.g. `create_new_project`). The project recommends the use of `black` but i'm not sure if the existing code is black-compliant.

I'm not recommending running `black` on the entire package - just on the docstrings for the external-facing functions. At the moment, the docstrings are a bit jarring to read so reformatting them would make them easier to digest in my personal opinion.

2022-04-22 16:25 UTC, MMathisLab approved these changes

2022-04-24 09:46 UTC, AlexEMG approved these changes
Thanks for your contribution!

2022-04-24 09:47 UTC, merged