Loosen pin on scikit-image
DeepLabCut/DeepLabCut pull request #1800
Opened 2022-04-24 19:41 UTC by hmaarrfk

There is quite some talk about what to do with scikit-image 1.0 in terms of compatibility.

This avoids many of these questions.

Hopefully the automated tests will find any bugs in terms of compatibility (there may be some) I'm happy to help with patching.

Closes https://github.com/DeepLabCut/DeepLabCut/issues/1791

2022-04-24 20:38 UTC, MMathisLab approved these changes

2022-04-25 11:40 UTC, jeylau requested changes
Hey @hmaarrfk, thanks for the PR! Could you also update the requirements.txt accordingly?

2022-04-25 12:26 UTC, hmaarrfk commented
```
 Processing...  /Users/runner/work/DeepLabCut/DeepLabCut/multi_mouse-dlc_team-2022-04-25/videos/m3v1mp4short.mp4
  0%|          | 0/5 [00:00<?, ?it/s]
100%|██████████| 5/5 [00:00<00:00, 6073.42it/s]
/Users/runner/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/deeplabcut/refine_training_dataset/stitch.py:676: UserWarning: No optimal solution found. Employing black magic...
```

I've seen this kind of failure before and it seem spurious. Is that correct?

2022-04-25 12:34 UTC, jeylau commented
> ```
>  Processing...  /Users/runner/work/DeepLabCut/DeepLabCut/multi_mouse-dlc_team-2022-04-25/videos/m3v1mp4short.mp4
>   0%|          | 0/5 [00:00<?, ?it/s]
> 100%|██████████| 5/5 [00:00<00:00, 6073.42it/s]
> /Users/runner/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/deeplabcut/refine_training_dataset/stitch.py:676: UserWarning: No optimal solution found. Employing black magic...
> ```
> 
> 
>     
>  
>   
> 
> I've seen this kind of failure before and it seem spurious. Is that correct?

Yes, no worries!

2022-04-25 12:34 UTC, merged