Adding a recipe for ModelZoo
DeepLabCut/DeepLabCut pull request #1962
Opened 2022-08-25 12:01 UTC by neslihanedes

2022-08-25 15:52 UTC, MMathisLab commented
Great contribution @neslihanedes ! I made a few edits that also also you to drop images from folder (to keep package lightweight). So, you can remove images and also rename file to `UsingModelZooPupil.md`? 🎉

2022-08-25 15:54 UTC, MMathisLab requested changes
- drop images, and rename file, and it looks good to me!

2022-08-25 19:48 UTC, AlexEMG approved these changes

2022-08-26 08:33 UTC, MMathisLab approved these changes

2022-08-26 10:23 UTC, merged