4 additional unit-tests
DeepLabCut/DeepLabCut pull request #2239
Opened 2023-05-11 08:56 UTC by AlexEMG

2023-05-11 09:05 UTC, jeylau requested changes

2023-05-11 09:05 UTC, jeylau commented on tests/test_frame_selection_tools.py
> +        (16, 100, 5, 0.25, 0.3, frame_index_2, valid_frame_index_2),  # 1600 frames at 16 fps -> 100 seconds
Can these multiple sets of parameters be moved outside the func in @pytest.mark.parametrize()?; e.g., as in https://github.com/DeepLabCut/DeepLabCut/blob/9fcf1f8ad9f04f2e23da74a3a9dc1463ee831c8f/tests/test_video.py#L76
When a unit test fails, this makes debugging easier.

2023-05-11 09:05 UTC, jeylau commented on tests/test_frame_selection_tools.py
> +        (16, 1600, 5, 0.25, 0.3, frame_index_2, valid_frame_index_2),  # 1600 frames at 16 fps -> 100 seconds
Same here.

2023-05-11 09:05 UTC, jeylau commented on tests/test_auxiliaryfunctions.py
> +    ]:
Same as below: let's use the `parametrize` fixture.

2023-05-11 09:06 UTC, jeylau commented
Awesome, just left minor comments.

2023-05-12 08:54 UTC, AlexEMG reviewed
Great!

2023-05-12 08:55 UTC, merged