Shaokai/sa transfer learning
DeepLabCut/DeepLabCut pull request #2389
Opened 2023-09-18 15:13 UTC by yeshaokai

SuperAnimal transfer learning API, example and docs

2023-09-21 08:11 UTC, jeylau commented on examples/openfield-Pranav-2018-10-30/config.yaml
> +    # Project definitions (do not edit)
I'd revert changes automatically made to this file.

2023-09-21 08:14 UTC, jeylau commented on examples/testscript_superanimal_transfer_learning.py
> +    config_path = os.path.join(os.getcwd(), "examples", "openfield-Pranav-2018-10-30", "config.yaml")
```suggestion
    basepath = os.path.dirname(os.path.realpath(__file__))
    config_path = os.path.join(basepath, "openfield-Pranav-2018-10-30", "config.yaml")
```

2023-09-21 08:15 UTC, jeylau requested changes
Two small changes to bring and looking good!

2023-09-21 10:19 UTC, yeshaokai commented
Changes made @jeylau

2023-09-21 10:34 UTC, jeylau approved these changes

2023-10-27 11:14 UTC, MMathisLab approved these changes

2023-10-27 11:15 UTC, MMathisLab commented
This looks great to me, with clear docs: all clear @n-poulsen / @AlexEMG ?

2023-10-30 13:57 UTC, n-poulsen requested changes
`black` needs to be run on the code, as there are a few style changes to update (i suggested some changes but there are more).

I'd also like us to change the commit history for the PR before merging. There are heavy artifacts that we added and then removed from the branch (removed in commits [removed artifacts](https://github.com/DeepLabCut/DeepLabCut/pull/2389/commits/3c745ea2ca5f159d99922344bfb8a767041409f9) and [removed more artifacts](https://github.com/DeepLabCut/DeepLabCut/pull/2389/commits/78b2591dfbcc6a84bdc5af21bed4d56d5700bc3a)), but they're still in the git history.

2023-10-30 13:57 UTC, n-poulsen commented on deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
> +
there should only be [2 blank lines](https://peps.python.org/pep-0008/#blank-lines) between functions :)

```suggestion
```

2023-10-30 13:57 UTC, n-poulsen commented on deeplabcut/generate_training_dataset/trainingsetmanipulation.py
> +
[2 blank lines](https://peps.python.org/pep-0008/#blank-lines) again


```suggestion
```

2023-10-30 13:57 UTC, n-poulsen commented on deeplabcut/generate_training_dataset/trainingsetmanipulation.py
> +    superanimal_name = ""
just a bit of styling to follow the rest of the file

```suggestion
    superanimal_name="",
```

2023-10-30 13:57 UTC, n-poulsen commented on deeplabcut/generate_training_dataset/trainingsetmanipulation.py
> +    if superanimal_name!="":
I think all these suggestions can be applied at once by running black on the code.

```suggestion
    if superanimal_name != "":
```

2023-10-30 13:57 UTC, n-poulsen commented on deeplabcut/generate_training_dataset/trainingsetmanipulation.py
> +        if not posecfg_template.endswith("pose_cfg.yaml") and not posecfg_template.endswith("superquadruped.yaml") and not posecfg_template.endswith("supertopview.yaml"):
this line is too long, apply `black`

2023-10-30 13:57 UTC, n-poulsen commented on deeplabcut/modelzoo/api/spatiotemporal_adapt.py
> +                print ('No data files found for plotting trajectory')
```suggestion
                print('No data files found for plotting trajectory')
```

2023-10-30 13:57 UTC, n-poulsen commented on deeplabcut/pose_estimation_tensorflow/core/train_multianimal.py
> +    trim_ends = None,  # trim the both ends of the video for video adaptation
`trim_ends` is not used in the function

2023-10-31 19:07 UTC, yeshaokai commented
@n-poulsen  ran black and removed unused parameters

2023-11-05 15:02 UTC, MMathisLab commented
Let's fix merge conflicts?

2023-11-06 10:20 UTC, jeylau commented
Thanks @yeshaokai for running black! I've fixed the merge conflict; looking good to me now.

2023-11-06 14:15 UTC, merged