Unifying docs on Napari DeepLabCut
DeepLabCut/DeepLabCut pull request #2399
Opened 2023-10-02 15:49 UTC by Timokleia

I updated the docs so the information and structure is unified.
I didnt touch the installation process at all (a bit different display between the two).
I deleted some old commits of mine - no relationship with the current work but they appear in the list.

2023-10-02 19:15 UTC, MMathisLab requested changes
- maybe check this one point, 
 - @Timokleia also lets link the new hotkey image in the docs?

2023-10-02 19:15 UTC, MMathisLab commented on docs/napariGUI.md
> +    ***As `viridis` is `napari-deeplabcut` default colormap, loading the config in the GUI is also needed to update the color scheme.***
I think this is now out of date with the new color picker, right @jeylau ?

2023-10-03 15:05 UTC, MMathisLab approved these changes

2023-10-04 09:48 UTC, merged

2023-10-04 10:46 UTC, Timokleia commented
@MMathisLab I am working on it this week. I will update - pls dont accept yet

2023-10-04 10:51 UTC, MMathisLab commented
I already edited it and merged, thanks @Timokleia