Fix bug dataset and metadataset fixes #2390
DeepLabCut/DeepLabCut pull request #2405
Opened 2023-10-05 11:19 UTC by Tetra-quark

2023-10-09 20:49 UTC, AlexEMG commented
Thanks!

2023-10-17 13:04 UTC, Tetra-quark commented
I have looked for other areas of the code that use `get_data_and_metadata_filenames` they are either related to dataset/metadataset file creation (no need to change these) or are test scripts where it matters less how these filenames are accessed.

However, `visualizemaps.py` should be updated given it's structural similiarity to `evaluate.py` and `evaluate_multianimal.py`. But before doing that I was hoping to get some feedback on the code review I opened above as it is also relevant to all three of the aforementioned files. 

I also wanted to note explicitly that my changes now mean that the 'metadataset' parameter in the train/pose_cfg.yaml is being accessed by modules that previously only accessed the test/pose_cfg.yaml. This is because while there is a 'dataset' parameter in the test/pose_cfg.yaml as far as I can see from the testing scripts there is no 'metadataset' parameter.

2023-10-27 12:43 UTC, jeylau requested changes
Thanks @Tetra-quark! I'd only ask you to load the train image indices outside the loop, and that looks great!

2023-10-27 12:43 UTC, jeylau commented on deeplabcut/pose_estimation_tensorflow/core/evaluate.py
> +                                )
I'd take this out of the loop to avoid loading the metadata over and over again.

2023-10-27 12:43 UTC, jeylau commented on deeplabcut/pose_estimation_tensorflow/core/evaluate.py
> +        Path(cfg["project_path"]) / train_pose_cfg["metadataset"],
I haven't tested it but is passing a `Path` instead of a `str` to `load_metadata()` fine?

2023-10-30 08:09 UTC, jeylau approved these changes

2023-10-30 08:11 UTC, jeylau commented
Great, thanks! I think this is good to merge, and if some code refactoring is needed in evaluate/visualizemaps, that can be done in a separate PR @MMathisLab @Tetra-quark.

2023-10-30 11:24 UTC, n-poulsen reviewed
Some minor stye comments, otherwise looks good to me

2023-10-30 11:24 UTC, n-poulsen commented on deeplabcut/pose_estimation_tensorflow/core/evaluate.py
> +import deeplabcut
I'm not a fan of importing all of `deeplabcut` in the `core/evaluate` code... would it perhaps be better to just import the module/method that we need?

I believe that here it's just for the `return_train_network_path` method, which could be imported as 
```python
from deeplabcut.pose_estimation_tensorflow.training import return_train_network_path
```

2023-10-30 11:24 UTC, n-poulsen commented on deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
> +            modelfolder_rel_path = auxiliaryfunctions.get_model_folder(trainFraction, shuffle, cfg, modelprefix=modelprefix)
`black` should be run on the code, as this line (and a few others) is too long

2023-12-07 00:56 UTC, merged