Test for the presence of snapshot files when using modelzoo
DeepLabCut/DeepLabCut pull request #2485
Opened 2024-01-15 10:50 UTC by jeylau

- Test early whether `superanimal` name is a valid option
- Test for the presence of model weight files rather than the only existence of a weight folder (so if the folder exists, but it does not contain any model snapshots, superanimal model weights will–as they should–be redownloaded, preventing the IndexError reported in other issues.)

Fixes #2469

2024-01-23 12:51 UTC, AlexEMG commented
Add comment here: raise ValueError(f"{superanimal_name} not available. Available ones are: ", MODELOPTIONS)

IF you see the model you want, go to the website and see what is available/upldate dlclib

2024-01-23 12:53 UTC, AlexEMG requested changes
Update comment as outlined.

2024-01-24 14:16 UTC, MMathisLab approved these changes

2024-02-08 11:00 UTC, n-poulsen approved these changes
Looks good to me!

2024-02-08 11:08 UTC, merged