Create tutorial
DeepLabCut/DeepLabCut pull request #2495
Opened 2024-01-24 10:40 UTC by Timokleia

Here is the branch with the tutorial I created. 
Please have a look and we can discuss how we proceed. 💪
For now I added all the images here but we can move afterwards.

2024-01-24 11:00 UTC, jeylau commented on docs/labelling.md
> +2. **Pick Frames Yourself:** Just like flipping through a photo album, you can go through your video and pick the frames that catch your eye. Choose the **`automatic`** extraction method.
```suggestion
2. **Pick Frames Yourself:** Just like flipping through a photo album, you can go through your video and pick the frames that catch your eye. Choose the **`manual`** extraction method.
```

2024-01-24 11:01 UTC, jeylau commented on docs/labelling.md
> +2. **Pick Frames Yourself:** Just like flipping through a photo album, you can go through your video and pick the frames that catch your eye. Choose the **`automatic`** extraction method.
I'd also add a sentence saying that it is important to ensure content diversity when manually picking frames to train robust models.

2024-01-24 11:06 UTC, jeylau commented on docs/Training-Evaluation.md
> +
```suggestion
```

2024-01-24 11:07 UTC, jeylau commented on docs/beginners-guide.md
> +conda activate DeepLabCut
```suggestion
conda activate DEEPLABCUT
```

2024-01-24 11:08 UTC, jeylau commented on docs/beginners-guide.md
> +When you first launch the GUI, you'll come across three primary main options:
```suggestion
When you first launch the GUI, you'll find three primary main options:
```

2024-01-24 11:09 UTC, jeylau commented on docs/beginners-guide.md
> +
```suggestion
```

2024-01-24 11:09 UTC, jeylau commented on docs/labelling.md
> +
```suggestion
```

2024-01-24 11:10 UTC, jeylau requested changes, later dismissed
Great, Tim! I've just suggested minor edits.

2024-06-05 09:17 UTC, MMathisLab approved these changes

2024-06-05 09:42 UTC, MMathisLab approved these changes

2024-06-07 17:15 UTC, n-poulsen approved these changes
LGTM!

2024-06-07 17:36 UTC, MMathisLab approved these changes

2024-06-07 17:37 UTC, merged