Update setup.py
DeepLabCut/DeepLabCut pull request #2526
Opened 2024-02-19 14:03 UTC by MMathisLab

- update pyside6

2024-03-01 12:52 UTC, MMathisLab commented
done? cc @n-poulsen

2024-03-05 14:17 UTC, n-poulsen commented
@MMathisLab I believe we need a new `napari-deeplabcut` release (version `0.2.1.5`) including the updates made in [#115](https://github.com/DeepLabCut/napari-deeplabcut/pull/115) and [#118](https://github.com/DeepLabCut/napari-deeplabcut/pull/118) before we can merge this. 

There are a few bugs with `napari-deeplabcut==0.2.1.3` and `pyside6==6.4.2` that have been fixed.

2024-03-05 14:41 UTC, MMathisLab commented
okay can you make a release?

2024-03-05 16:17 UTC, n-poulsen requested changes
Tested with Python 3.10 and 3.11. I found one issue; when selecting the "Show trails" checkbox, the napari window goes blank. This is easily solved by resizing the window, but I'll open an issue about this so people have somewhere to go for a quick fix (once this PR is merged).

---

I'm also getting a warning when installing the `apple_mchips` extra:

```
WARNING: deeplabcut 2.3.9 does not provide the extra 'apple-mchips'
```

I believe this is the same `pip` issue as we saw with `napari-deeplabcut` (changes to the way underscores are transformed into dashes), and we can solve it by renaming the extra to `apple-mchips`. Currently not an issue as tensorflow is still installed correctly, despite the warning.

2024-03-05 16:17 UTC, n-poulsen commented on setup.py
> +            "napari-deeplabcut>=0.2.1.4",
Update for the [latest release](https://pypi.org/project/napari-deeplabcut/#history)

```suggestion
            "napari-deeplabcut>=0.2.1.5",
```

2024-04-03 15:54 UTC, jeylau commented on setup.py
> +            "napari-deeplabcut>=0.2.1.5",
```suggestion
            "napari-deeplabcut>=0.2.1.6",
```

2024-04-03 15:56 UTC, jeylau commented
I've just pushed a new release (0.2.1.6) of napari-deeplabcut, that includes our latest fixes/improvements.
This is ready to merge after the setup.py 😊

2024-04-16 13:49 UTC, MMathisLab commented
I guess now we can merge, or no?

2024-04-16 13:50 UTC, jeylau commented
@MMathisLab, yes, that looks good to me!

2024-04-17 11:45 UTC, n-poulsen approved these changes

2024-04-17 12:03 UTC, merged