Make 3D Triangulate possible with pytorch_dlc branch and MA project
DeepLabCut/DeepLabCut pull request #2729
Opened 2024-09-02 05:59 UTC by Zelin2001

## Rationality

I proceeded with my project, and then found the `triangulate()` function dependent on TensorFlow modules. Further debugging revealed more problems relating to the 'single' individual, who has a different bodypart dimension from common individuals.

Finally, I made minor changes to make triangulation work on my dataset. These changes might also help with other 3D MA users.

## Changes

- Compute triangulated data with pose_estimation_pytorch

- Make correct MultiIndex with unique bodyparts

- adapt to DataFrame.to_hdf() changes

2024-09-05 15:48 UTC, MMathisLab commented
thanks so much for your contribution! This is super helpful!

2024-09-05 15:52 UTC, MMathisLab approved these changes

2024-09-06 15:02 UTC, n-poulsen requested changes
Thanks @Zelin2001, this looks great! Just suggested a few changes, let me know if you want to discuss anything.

One the changes are made this looks good to me :)

2024-09-06 15:02 UTC, n-poulsen commented on deeplabcut/pose_estimation_3d/triangulation.py
> +# from matplotlib.axes._axes import _log as matplotlib_axes_logger
If we want to change the logging level I'd prefer removing the lines entirely rather than commenting them :)

```suggestion
```

2024-09-06 15:02 UTC, n-poulsen commented on deeplabcut/pose_estimation_3d/triangulation.py
> +# matplotlib_axes_logger.setLevel("ERROR")
same comment as above :)

```suggestion
```

2024-09-06 15:02 UTC, n-poulsen commented on deeplabcut/pose_estimation_3d/triangulation.py
> +    from deeplabcut.pose_estimation_pytorch import analyze_videos
I believe this should be updated to import analyze_videos from the `compat` module. This will make the code compatible with both `PyTorch` and `TensorFlow` DeepLabCut models, as it will select which to use based on the shuffle/which type of model was trained

```suggestion
    from deeplabcut.compat import analyze_videos
```

2024-09-06 15:02 UTC, n-poulsen commented on deeplabcut/pose_estimation_3d/triangulation.py
> -                            gputouse=gputouse,
If we import `analyze_videos` from the `compat` module as described above, we can keep the `gputouse` parameter as it will be handled correctly (see this [bit of code](https://github.com/DeepLabCut/DeepLabCut/blob/78cc44eaea296fc2a6f8979027497298348359aa/deeplabcut/compat.py#L849)).

This will allow users to continue choosing on which GPU they want to run video analysis :)

2024-09-06 15:02 UTC, n-poulsen commented on deeplabcut/pose_estimation_3d/triangulation.py
> -                        gputouse=gputouse,
Same comment as above :)

2024-09-07 07:39 UTC, Zelin2001 commented
> Thanks @Zelin2001, this looks great! Just suggested a few changes, let me know if you want to discuss anything.
> 
> One the changes are made this looks good to me :)

Thank you a lot for the advice @n-poulsen . I've learned more about deeplabcut from these changes.

2024-09-09 08:01 UTC, n-poulsen approved these changes
Looks good to me! Thanks @Zelin2001!

2024-09-09 16:38 UTC, merged