New Top-Down Pose Estimation Model - RTMPose
DeepLabCut/DeepLabCut pull request #2795
Opened 2024-11-25 14:37 UTC by n-poulsen

This pull requests adds the implementation for [RTMPose: Real-Time Multi-Person Pose Estimation based on MMPose](https://arxiv.org/pdf/2303.07399).

Full changes:

- New mixin for backbones with pretrained weights on [HuggingFace ](https://huggingface.co/DeepLabCut/DeepLabCut-Backbones): `HuggingFaceWeightsMixin`
- New backbone: `CSPNeXt`
- New head: `RTMCCHead`
- New target generator: `SimCCGenerator`
- New predictor: `SimCCPredictor`
- New weight initializer: `Rtmpose` 
- New `RandomBBoxTransform` augmentation for top-down models (jitters ground truth bounding boxes)
- Configs for `CSPNeXt` backbones: `cspnext_s`, `cspnext_m`, `cspnext_x`
- Configs for `RTMPose` models: `rtmpose_s`, `rtmpose_m`, `rtmpose_x`
- Updated way to scheduler configurations, to allow for the use of `SequentialLR` (to match the RTMPose training schedulers)
- Added documentation: using a `SequentialLR` scheduler for warm-up epochs
- Updated the top-down crop to function with no-square crops (and re-implemented with numpy)
  - Added `top_down_crop_size: (crop_w, crop_h)` and ` top_down_crop_margin` in the `pytorch_config.yaml` file for an easy way to control the size of the crops for top-down models.
- Bug fix: `bbox_from_keypoints` when there's more than 1 individual (bug had no impact as method was always called in a way it wouldn't fail)

2024-12-10 05:25 UTC, maximpavliv requested changes

2024-12-10 05:25 UTC, maximpavliv commented on deeplabcut/pose_estimation_pytorch/config/rtmpose/rtmpose_x.yaml
> +model:  # https://github.com/open-mmlab/mmpose/blob/main/projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-x_8xb256-700e_coco-384x288.py
Has the comment been added on purpose here or is it a mistake?
What about other comments in the model configurations (`# Need to add a detector` etc)?

2024-12-10 05:25 UTC, maximpavliv commented on deeplabcut/pose_estimation_pytorch/data/dataset.py
>      _extract_keypoints_and_bboxes,
Should we remove the underscore from these methods names (and add a backwards compatibility update line)?

2024-12-10 05:25 UTC, maximpavliv commented on deeplabcut/pose_estimation_pytorch/data/transforms.py
> +        # TODO(niels): should bboxes width and height be scaled with same value?
Should we address this comment before merging?

2024-12-10 05:25 UTC, maximpavliv commented on deeplabcut/pose_estimation_pytorch/models/weight_init.py
> +import torch.nn
Let's either remove this line or the line just below

2024-12-10 05:25 UTC, maximpavliv commented on tests/pose_estimation_pytorch/data/test_transforms.py
> +    bboxes[:, 2:] = (image_wh - bboxes[:, :2]) * gen.random((num_bboxes, 2))
The bboxes generation is duplicated across tests, let's move this out into a separate method?

2024-12-10 08:30 UTC, n-poulsen commented on deeplabcut/pose_estimation_pytorch/data/dataset.py
>      _extract_keypoints_and_bboxes,
we can and probably should, in a bigger refactor of the dataset class; but this shouldn't be done in this pull request as it concerns other parts of the code (and not RTMPose implementation)

2024-12-10 13:25 UTC, n-poulsen commented on deeplabcut/pose_estimation_pytorch/config/rtmpose/rtmpose_x.yaml
> +model:  # https://github.com/open-mmlab/mmpose/blob/main/projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-x_8xb256-700e_coco-384x288.py
The github link is forgotten, I'll remove it; the `detector` comment is added for all top-down models before a detector is added

2024-12-10 13:31 UTC, n-poulsen commented on deeplabcut/pose_estimation_pytorch/data/transforms.py
> +        # TODO(niels): should bboxes width and height be scaled with same value?
Yes I tested that but forgot the todo - I'll take care of it

2024-12-18 16:46 UTC, maximpavliv approved these changes
Great!!

2024-12-20 15:40 UTC, merged