Model Output Visualization for PyTorch Models
DeepLabCut/DeepLabCut pull request #2799
Opened 2024-11-29 16:04 UTC by n-poulsen

This pull request implements methods to visualize maps output by PyTorch models (scoremaps, location refinement fields and part-affinity fields) as they are for TensorFlow models.

## API Methods Implemented for the PyTorch Engine

- `extract_maps`
- `visualize_scoremaps`
- `visualize_locrefs`
- `visualize_paf`
- `extract_save_all_maps`

## UX Improvements

- only start training pose models when `epochs > 0`
- `get_model_snapshots`: when no snapshots were found, the snapshot manager's snapshot prefix was obtained incorrectly
- fine-tuning SuperAnimal detectors: added `key_metric` so the best detector si saved

2024-12-01 19:29 UTC, MMathisLab commented
@maximpavliv please test; I won't have time in the next days.

2024-12-02 10:08 UTC, maximpavliv requested changes
Some minor corrections :)

2024-12-02 10:08 UTC, maximpavliv commented on deeplabcut/compat.py
>      an error if called with a PyTorch shuffle.
Remove the warning, and maybe a little description instead would be great

2024-12-02 10:08 UTC, maximpavliv commented on deeplabcut/compat.py
>      an error if called with a PyTorch shuffle.
Same here

2024-12-02 10:08 UTC, maximpavliv commented on deeplabcut/compat.py
>      """
In the docstring below, remove _"This function is only implemented for tensorflow models/shuffles, and will throw an error if called with a PyTorch shuffle."_

2024-12-02 10:08 UTC, maximpavliv commented on deeplabcut/compat.py
>      modelprefix: str = "",
In the docstring below, remove _"This function is only implemented for tensorflow models/shuffles, and will throw an error if called with a PyTorch shuffle."_

2024-12-02 10:08 UTC, maximpavliv commented on deeplabcut/pose_estimation_pytorch/runners/inference.py
>          """
Add Path to the argument type suggestions

2024-12-02 10:08 UTC, maximpavliv commented on docs/pytorch/user_guide.md
> +PyTorch, as well as indications which options are not yet implemented, and which
```suggestion
PyTorch API, as well as indications which options are not yet implemented, and which
```
I think that there is a word missing, API / version / release ?

2024-12-02 12:24 UTC, n-poulsen commented
@maximpavliv good catches, thanks! I implemented the fixes from your suggestions

2024-12-02 12:37 UTC, maximpavliv requested changes

2024-12-02 12:37 UTC, maximpavliv commented on deeplabcut/compat.py
> +        extract_maps(
```suggestion
        return extract_maps(
```
Otherwise it ends in the `raise NotImplementedError(...)`

2024-12-02 12:56 UTC, maximpavliv approved these changes

2024-12-02 12:56 UTC, merged