Implement missing arguments for PyTorch models
DeepLabCut/DeepLabCut pull request #2816
Opened 2024-12-16 15:53 UTC by n-poulsen

This pull request implements features for API methods that were not yet available for PyTorch models.

 ##  `deeplabcut.analyze_images`

The `analyze_time_lapse_frames` method is added to the PyTorch API, such that it can be called with PyTorch models in the same way as it was for TensorFlow models. Below the hood, it calls the `analyze_images` method.

The `analyze_images` (which can only be called for PyTorch models - `analyze_time_lapse_frames` should still be used for TensorFlow models) is added to the `compat.py` so that it can be called as:

```python
import deeplabcut

deeplabcut.analyze_images(
    config="path/to/my/project/config.yaml",
    images="/my/image/dir",
    shuffle=12,
)
```

New features are also added to the `analyze_images` method as well:
- Predictions can directly be plot onto images through the `plotting` parameter. Predictions are plot in the same format as when called with `evaluate_network`, the only difference being there is no ground truth to plot. The plotting parameters are taken from the project configuration file, and `pcutoff`, `bbox_pcutoff` and `plot_skeleton` allow to dynamically edit some of the parameters controlling plotting. 
- The predictions are now stored as a pandas `DataFrame`, as with other outputs in DeepLabCut. The predictions can also be saved in `CSV` files with the `save_as_csv` parameter.

## `deeplabcut.analyze_videos`

The `in_random_order` and `n_tracks` parameters are implemented for video analysis with PyTorch models.

Dynamic cropping (through the `dynamic` argument) is now available for `analyze_videos ` with PyTorch models. This function is implemented through a `DynamicCropper` cropper class, which is fully tested.

The `greedy`, `calibrate` and `window_size` arguments still need to be implemented. They are only valid for PAF-models, and require that more information is added to the `_full.pickle` file when running video analysis. This will be done in a subsequent pull request.

## `deeplabcut.train_network`

The `keepdeconvweights` argument is implemented, which allows to continue. Two additional arguments are added to the method: `epochs` and `save_epochs`. These arguments could already be passed, but making them explicit makes it clearer for users how they can be used.

2024-12-18 17:34 UTC, maximpavliv requested changes

2024-12-18 17:34 UTC, maximpavliv commented on deeplabcut/compat.py
> +
```suggestion
    epochs: optional, default=None
        Only for the PyTorch engine (equivalent to the `maxiters` parameter for the
        TensorFlow engine). The maximum number of epochs to train the model for. If
        None, the value will be read from the `pytorch_config.yaml` file. An epoch is a
        single pass through the training dataset, which means your model has seen each
        training image exactly once. So if you have 64 training images for your network,
        an epoch is 64 iterations with batch size 1 (or 32 iterations with batch size 2,
        16 with batch size 4, etc.).

    save_epochs: optional, default=None
        Only for the PyTorch engine (equivalent to the `saveiters` parameter for the
        TensorFlow engine). The number of epochs between each snapshot save. If
        None, the value will be read from the `pytorch_config.yaml` file.
```

2024-12-18 17:34 UTC, maximpavliv commented on deeplabcut/compat.py
> +        By default, the models are assumed to exist in the project folder.
```suggestion
    save_as_csv: bool, optional
        Saves the predictions in a .csv file. The default is ``False``; if provided it
        must be either ``True`` or ``False``.

    modelprefix: str, optional
        Directory containing the deeplabcut models to use when running image analysis.
        By default, the models are assumed to exist in the project folder.

    plotting: bool, str, default=False
        Plots the predictions made by the model on the analyzed images. Results will be
        stored in a folder named `LabeledImages_{scorer}`, where scorer is the name
        of the model used to analyze the images. This folder will be in the same
        directory as the file containing the predictions (either the given `destfolder`,
        or the folder containing the first image to analyze).

        If provided it must be either ``True``, ``False``, ``"bodypart"``, or
        ``"individual"``. Setting to ``True`` defaults as ``"bodypart"`` for
        multi-animal projects. If a detector is used, the predicted bounding boxes
        will also be plotted.

    pcutoff: float, optional, default=None
        The cutoff score when plotting pose predictions. Must be None or in
        (0, 1). If None, the pcutoff is read from the project configuration file.

    bbox_pcutoff: float, optional, default=None
        The cutoff score when plotting bounding box predictions. Must be
        None or in (0, 1). If None, it is read from the project configuration file.

    plot_skeleton: bool, default=False
        If a skeleton is defined in the project's config.yaml, whether
        to plot the skeleton connecting the predicted bodyparts on the images.
```

2024-12-18 17:34 UTC, maximpavliv commented on deeplabcut/compat.py
> +        analyze_images(
```suggestion
        return analyze_images(
```

2024-12-18 17:34 UTC, maximpavliv commented on deeplabcut/compat.py
>      an error if called with a PyTorch shuffle.
```suggestion
```

2024-12-18 17:34 UTC, maximpavliv commented on deeplabcut/pose_estimation_pytorch/apis/convert_detections_to_tracklets.py
> +    window_size: int = 0,  # TODO: Unused, remove
These arguments are planned to be added, right? Then maybe we should update the comments, to say that it isn't implemented yet, but will in the future

2024-12-18 17:34 UTC, maximpavliv commented on docs/pytorch/user_guide.md
> +| `analyze_videos`               |     🟠      | `calibrate`                                                                                         |
```suggestion
| `analyze_videos`               |     🟠      | `greedy`, `calibrate`, `window_size`                                                                |                                                     |
```

2024-12-19 13:01 UTC, n-poulsen commented on deeplabcut/pose_estimation_pytorch/apis/convert_detections_to_tracklets.py
> +    window_size: int = 0,  # TODO: Unused, remove
Yes those will be added in a subsequent pull request.

```suggestion
    greedy: bool = False,  # TODO(niels): implement greedy assembly during video analysis
    calibrate: bool = False,  # TODO(niels): implement assembly calibration during video analysis
    window_size: int = 0,  # TODO(niels): implement window size selection for assembly during video analysis
```

2024-12-19 13:16 UTC, maximpavliv approved these changes
LGTM!

2024-12-19 17:31 UTC, merged