Fix for negative coordinates in the dataset
DeepLabCut/DeepLabCut pull request #501
Opened 2019-11-22 00:59 UTC by ThejanW

Fix for issue #493 

Apparently, few of my annotations are having negative coordinates. I've changed trainingsetmanipulation.py to not to add such examples to the dataset.

Ubuntu 18.04
tensorflow-gpu==1.14
CUDA 10
GeForce RTX 2080 Ti

How to test: 

- Please download the .csv and .h5 files from this [link](https://drive.google.com/drive/folders/1t69jf0hl2u-odIvS5ImxZff-gN6hBCMf?usp=sharing)
- You can use those with **examples/Reaching-Mackenzie-2018-08-30**. This .csv has few negative coordinates to reproduce this behavior.   
- I have added few prints for debugging purposes. Will remove them once you test this.

[testscript.log](https://github.com/AlexEMG/DeepLabCut/files/3877415/testscript.log)

2019-11-22 01:08 UTC, ThejanW commented
Here's a sample output of the prints.

![image](https://user-images.githubusercontent.com/17251474/69389637-a189c100-0cf2-11ea-98ec-83482047f4de.png)

2019-11-22 19:58 UTC, AlexEMG commented
I think both the x & y coordinate should be removed. Also, I think it would be better to fix the issue in the loader itself. I.e. check for corrupt frames (post augmentation).

2019-11-22 20:18 UTC, ThejanW commented
Hi @AlexEMG. Both x and y get removed with this line,
```
 joints = joints[np.where(
                    np.prod(np.isfinite(joints),
                            1))[0], :]
```

2019-11-22 22:29 UTC, ThejanW commented
A case where only x is negative,
![image](https://user-images.githubusercontent.com/17251474/69464449-61831680-0da4-11ea-8fe6-e966331761e3.png)

A case where only y is negative,
![image](https://user-images.githubusercontent.com/17251474/69464471-6f389c00-0da4-11ea-845d-eaad1d6bd25a.png)

A case where both x and y are negative,
![image](https://user-images.githubusercontent.com/17251474/69464563-a27b2b00-0da4-11ea-8dfe-757dabb4d5ff.png)

Do you suggest editing these source files to not to load corrupted frames?
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/dataset/pose_defaultdataset.py
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset_deterministic.py
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset_imgaug.py
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset_tensorpack.py

2019-11-22 22:38 UTC, AlexEMG requested changes
In Line 644 we check if data points are smaller than image size. (if Data[bodypart]['x'][jj]<np.shape(im)[1] and Data[bodypart]['y'][jj]<np.shape(im)[0]:) 

I think one could add the ">=0" case there as well.

2019-11-23 21:51 UTC, ThejanW commented
@AlexEMG Thanks for your input. I've made the suggested changes. Please review and merge.

2019-11-23 22:25 UTC, AlexEMG approved these changes

2019-11-23 22:25 UTC, merged